### ISSUE TITLE
Error in .importMsigDBGMT(file) : This does not work at the present.

### ISSUE THREAD

**Issue by Dereth-Pirout** [january3/tmod#1]
Hi,

I was trying to use tmodImportMSigDB() to load a .gmt file into a tmod object and I am seeing this error message:

> mappings <- tmodImportMSigDB(file = annotation_file_local, format = "gmt")
Error in .importMsigDBGMT(file) : This does not work at the present.

Could you tell me more about this error message?

**Comment by Dereth-Pirout** [comment]
It turned out to be a version issue.

**Comment by Dereth-Pirout** [comment]
It turned out to be a version issue.

**Comment by hannalemmik** [comment]
@Dereth-Pirout Hey, I am having the same issue. How did you fix it? Tried all tmod versions and kept coming up with the same error.

**Comment by hannalemmik** [comment]
Actually, for anyone encountering this, I solved the issue by having version 0.40 of tmod.
install.packages("remotes")
library(remotes)
install_version("tmod", "0.40")
